### ISSUE TITLE
Suggestion: Have it parse and store the username

### ISSUE THREAD

**Issue by drazisil** [TheRealJoeLinux/circlecli#2]
IIRC, tokens are only per user. Therefore, once the token is saved, the user shouldn't change or need to be provided by the user again.

Username can be pulled from /me on first use, so user may never need to provide it.

**Comment by particledecay** [comment]
I wonder if you're confusing the default_username with the user account the token is attached to (the account when you call `/me`). The only thing the default_username setting is for is when most of your CircleCI projects have the same owner, and you don't feel like specifying it each time.

Say your user account is "foo_user", and you are part of a GitHub organization "IHOP". Most of your CircleCI projects are for repos owned by "IHOP" ("IHOP/pancakes", "IHOP/shakes", "IHOP/french_toast"), and so you don't want to specify `-u IHOP` all the time. But when you call `/me`, it's going to show you the account info for "foo_user". Unfortunately, CircleCI references the owner of a repo/project as "username" in their docs, so that's why I kept that reference as "default_username". I think it's confusing, but I wanted to stay as close to their naming conventions as possible.

**Comment by drazisil** [comment]
Wasn't confusing them, just forgot that /me doesn't require a token, I was thinking that it would show the username attached to the token.

Since there is no way to tell what username a token is attached to (likely for security reasons), closing issue.
