### ISSUE TITLE
Feature: Add ability to provide token as an env 

### ISSUE THREAD

**Issue by drazisil** [TheRealJoeLinux/circlecli#4]
I can see this tool being used in circle.yml files. It would be good if it can read the api token from an env, preventing the token from being saved in a public file as part of the project.

**Comment by particledecay** [comment]
Yep, this makes sense. Also, the token is never saved as part of the project. It's saved in a config file in your user's home directory.

If I went this route... there are three approaches I can think of:
1. Use the config file, but allow something like `ENV['CIRCLE_TOKEN']` to be input instead of the actual token; or
2. Provide the environment variable on each run (don't like this); or
3. Go with a predetermined environment variable (such as "CIRCLE_TOKEN"), and if it doesn't exist, then check the config file for it.

I'm leaning toward #3.

**Comment by drazisil** [comment]
>  It's saved in a config file in your user's home directory

That doesn't persist if used via CI, and still has to come from somewhere :)

#3 seems fine.

**Comment by particledecay** [comment]
@drazisil This should be working in the latest release. Check it out!
